// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/bun";
import { Hono } from 'hono'
import { createMiddleware } from "hono/factory";
import { createContext, RouterContextProvider, } from "react-router";

export interface AppContext {
    appVersion: 'dev' | 'production' | undefined,
}

export const appContext = createContext<AppContext | null>(null);

const honoLogger = createMiddleware(async (c, next) => {
    const start = Date.now();
    await next();
    const dur = Date.now() - start;
    // You can swap for a real logger
    console.log(`[Hono] ${c.req.method} ${c.req.path} -> ${c.res.status} ${dur}ms`);
});

const app = new Hono()

export default await createHonoServer({
    app,
    configure(server) {
        server.use("*", honoLogger);
    },
    getLoadContext (c, { mode, build }) {
        const isProductionMode = mode === "production";
        const context = new RouterContextProvider();
        context.set(appContext, { 
            appVersion: isProductionMode ? "production" : "dev", 
        })
        return context;
    }
});
